# Generated by Django 5.2.1 on 2025-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
