# Generated by Django 5.2.1 on 2025-05-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
